In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import regex
import sys
import warnings
warnings.filterwarnings('ignore')

In [7]:
# read excel file
path =r"C:\Users\vho2\3D Objects\test.xlsx"
df = pd.read_excel(path, sheet_name='metadata')
df.head(10)

,DbIndex,Name,ExternalId,Elevation,Computation Height,Scope Box,Export to IFC,IfcGUID,Structural,Building Story,...,Schedule Footer Notes,Neutral Rating,Neutral Bus,Ground Bus,Bussing,Mains Type,Wattage,Mounting Height,Placement Height,Filter
0,2,Level 1,9693c920-050e-4443-9b38-2491295576d1-00000163,0.0,0.0,None,By Type,2MayaW1Gv4Gviu994fLNUo,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,Level 2,9693c920-050e-4443-9b38-2491295576d1-00000aea,3048.0,0.0,None,By Type,2MayaW1Gv4Gviu994fLNmx,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,Level 04 - T.O. Fnd. Wall,eabed363-0187-429d-91a7-2d7d264a1a0c-000015ba,-304.8,0.0,None,By Type,3gljDZ0OT2dP6dBNqcIW_s,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,Level 03 - T.O. Basement Slab,eabed363-0187-429d-91a7-2d7d264a1a0c-000015e8,-2438.4,0.0,None,By Type,3gljDZ0OT2dP6dBNqcIW$a,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6,Level 02 - T.O. Footing,eabed363-0187-429d-91a7-2d7d264a1a0c-000015ff,-2743.2,0.0,None,By Type,3gljDZ0OT2dP6dBNqcIW$p,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,7,Level 01 - B.O. Footing,eabed363-0187-429d-91a7-2d7d264a1a0c-0000161d,-3048.0,0.0,None,By Type,3gljDZ0OT2dP6dBNqcIWmH,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,8,Roof,f440c2b6-09c3-46da-b5c7-670feedae5cf-00002268,6096.0,0.0,None,By Type,3qGCAs2SD6shN7Pm$ksiUd,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,9,Level 1,9693c920-050e-4443-9b38-2491295576d1-00000164,NaN,NaN,None,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,10,Level 1,8ba265ee-debf-4b65-a77a-52060c81238b-0000016a,NaN,NaN,None,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,11,East,9693c920-050e-4443-9b38-2491295576d1-000008bb,NaN,NaN,None,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
## get all column name 
parameters = df.columns
# create a series of parameters
parameters = pd.Series(parameters)
# drop the first column name
parameters = parameters.drop(0)
# reset index
parameters = parameters.reset_index(drop=True)
print("Total Flattented Parameters: ", len(parameters))

Total Flattented Parameters:  687

In [10]:
# get Dbindex = 1328
df1 = df.loc[df['DbIndex'] == 3528]
df1 = df1.reset_index(drop=True)
# convert to series
df1 = df1.squeeze()
# remove all nan 
df1 = df1.dropna()
df1

DbIndex                                                                    3528
Name                                     Seating-LAMMHULTS-PENNE-Chair [289790]
ExternalId                        5bb069ca-e4fe-4e63-be31-f8ac44e80d30-00046bfe
Export to IFC                                                           By Type
IfcGUID                                                  1Ri6dAvFvEOxun_An4x6RE
Workset                       Family  : Furniture : Seating-LAMMHULTS-PENNE-...
Comments                                                        This is a chair
Type Name                                                          Plastic-Seat
Host                                                            Level : Level 1
Room Name                                                                 Sleep
Room Number                                                                A001
Moves With Nearby Elements                                                  0.0
Level                                                                   Level 1
Phase Created                                                Project Completion
Phase Demolished                                                           None
Elevation from Level                                                        0.0
Offset from Host                                                            0.0
Armrest Left                                                                0.0
Armrest Right                                                               0.0
Name: 0, dtype: object

In [11]:
import re
import warnings
warnings.filterwarnings("ignore")
# find element ids inside column Name from dataframe df
# eg: Seating-LAMMHULTS-PENNE-Chair [289790]  => 289790
pattern = r'\[(.*?)\]'
element_ids = df["Name"].str.findall(pattern)
element_ids = element_ids.str[0].str.replace(r'\[|\]', '')
if "ElementID" in df.columns:
    df["ElementID"] = element_ids
else:
    df.insert(2, "ElementID", element_ids)
df

,DbIndex,Name,ElementID,ExternalId,Elevation,Computation Height,Scope Box,Export to IFC,IfcGUID,Structural,...,Schedule Footer Notes,Neutral Rating,Neutral Bus,Ground Bus,Bussing,Mains Type,Wattage,Mounting Height,Placement Height,Filter
0,2,Level 1,NaN,9693c920-050e-4443-9b38-2491295576d1-00000163,0.0,0.0,None,By Type,2MayaW1Gv4Gviu994fLNUo,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,Level 2,NaN,9693c920-050e-4443-9b38-2491295576d1-00000aea,3048.0,0.0,None,By Type,2MayaW1Gv4Gviu994fLNmx,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,Level 04 - T.O. Fnd. Wall,NaN,eabed363-0187-429d-91a7-2d7d264a1a0c-000015ba,-304.8,0.0,None,By Type,3gljDZ0OT2dP6dBNqcIW_s,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,Level 03 - T.O. Basement Slab,NaN,eabed363-0187-429d-91a7-2d7d264a1a0c-000015e8,-2438.4,0.0,None,By Type,3gljDZ0OT2dP6dBNqcIW$a,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6,Level 02 - T.O. Footing,NaN,eabed363-0187-429d-91a7-2d7d264a1a0c-000015ff,-2743.2,0.0,None,By Type,3gljDZ0OT2dP6dBNqcIW$p,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4053,4195,Project Completion [311598],311598,27808218-035f-41e4-8acb-f742c50c8d6a-0004c12e,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4054,4196,[311599],311599,27808218-035f-41e4-8acb-f742c50c8d6a-0004c12f,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4055,4197,Level 02 - T.O. Footing [311600],311600,27808218-035f-41e4-8acb-f742c50c8d6a-0004c130,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4056,4198,Level 02 - T.O. Footing [311601],311601,27808218-035f-41e4-8acb-f742c50c8d6a-0004c131,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4057,4199,LMV [311602],311602,27808218-035f-41e4-8acb-f742c50c8d6a-0004c132,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
# now we know how many element ids in the dataframe
elements = df["ElementID"].unique()
# remove all nan
elements = elements[~pd.isnull(elements)]
elements = elements.astype(int)
print("Total Element IDs: ", len(elements))

Total Element IDs:  3822

In [27]:
# try get all values have parameters comments 
comments = df["Comments"].unique()
# remove all nan
comments = comments[~pd.isnull(comments)]
# create a series of comments
comments = pd.Series(comments)
comments

0    This is a chair
1      This is a bed
2    Room Just Sleep
dtype: object